# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.EmailField(max_length=254),
        ),
    ]
